# This file is automatically generated. Please do not modify.

from . import AsciiArt

codex_linux = AsciiArt(match=r'''"Codex Linux"*''', color='fg', ascii=r"""
${c1}#:              :+#@@@@%#
@@#:          .*@@@@@@@@@
@@@@#-       .@@@@@@@@@@@
@@@@@@%-     %@@@@@@@@@@@
@@@@@@@@%=  :@@@@%%%%@@@@
@@@@@@@@@@%==*-:     .:=#
:*@@@@@@@@@@=
  :*@@@@@@@@=
    .*@@@@@@=
      .+@@@@=
        .+%@=
           +=
""")
    