# This file is automatically generated. Please do not modify.

from . import AsciiArt

q4os = AsciiArt(match=r'''"Blackberry 10"* | "QNX"*''', color='1', ascii=r"""
${c1}    .KMMMMMbo     .KMMMMMbo
    aMMMMMMMMb    aMMMMMMMMb
   ,KMMMMMMMMp   ,KMMMMMMMMp
   AMMMMMMMP*    AMMMMMMMP*   ,KMMMMMbo
                              aMMMMMMMMb
 .KMMMMMbo     .KMMMMMbo     .KMMMMMMMMp
 aMMMMMMMMb    aMMMMMMMMb    AMMMMMMMP*
,KMMMMMMMMp   .KMMMMMMMMp
AMMMMMMMP*    AMMMMMMMP*    .KMMMMMbo
                            aMMMMMMMMb
            .KMMMMMbo      ,KMMMMMMMMp
            aMMMMMMMMb     AMMMMMMMP*
           ,KMMMMMMMMp
           AMMMMMMMP*
""")
